// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calebtracey/go-scraper/internal/services/scrape (interfaces: ServiceI)

// Package scrape is a generated GoMock package.
package scrape

import (
	reflect "reflect"

	models "github.com/calebtracey/go-scraper/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockServiceI is a mock of ServiceI interface.
type MockServiceI struct {
	ctrl     *gomock.Controller
	recorder *MockServiceIMockRecorder
}

// MockServiceIMockRecorder is the mock recorder for MockServiceI.
type MockServiceIMockRecorder struct {
	mock *MockServiceI
}

// NewMockServiceI creates a new mock instance.
func NewMockServiceI(ctrl *gomock.Controller) *MockServiceI {
	mock := &MockServiceI{ctrl: ctrl}
	mock.recorder = &MockServiceIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceI) EXPECT() *MockServiceIMockRecorder {
	return m.recorder
}

// ScrapeCommonData mocks base method.
func (m *MockServiceI) ScrapeCommonData(arg0 string) ([]models.Data, []error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScrapeCommonData", arg0)
	ret0, _ := ret[0].([]models.Data)
	ret1, _ := ret[1].([]error)
	return ret0, ret1
}

// ScrapeCommonData indicates an expected call of ScrapeCommonData.
func (mr *MockServiceIMockRecorder) ScrapeCommonData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScrapeCommonData", reflect.TypeOf((*MockServiceI)(nil).ScrapeCommonData), arg0)
}
