Env: "local"
Port: "6080"
AppName: "go-scraper"
ClientConfig:
  Timeout: 15
  IdleConnTimeout: 30
  MaxIdleConsPerHost: 1
  MaxConsPerHost: 1
DatabaseConfigs:
ServiceConfigs:
  - Name: "GEOCODING"
    ApiKeyEnvironmentVariable: "GEOCODING_API_KEY"
