// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calebtracey/go-scraper/internal/services/googlemaps (interfaces: ServiceI)

// Package googlemaps is a generated GoMock package.
package googlemaps

import (
	context "context"
	reflect "reflect"

	models "github.com/calebtracey/go-scraper/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockServiceI is a mock of ServiceI interface.
type MockServiceI struct {
	ctrl     *gomock.Controller
	recorder *MockServiceIMockRecorder
}

// MockServiceIMockRecorder is the mock recorder for MockServiceI.
type MockServiceIMockRecorder struct {
	mock *MockServiceI
}

// NewMockServiceI creates a new mock instance.
func NewMockServiceI(ctrl *gomock.Controller) *MockServiceI {
	mock := &MockServiceI{ctrl: ctrl}
	mock.recorder = &MockServiceIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceI) EXPECT() *MockServiceIMockRecorder {
	return m.recorder
}

// GeocodeLocationAddress mocks base method.
func (m *MockServiceI) GeocodeLocationAddress(arg0 context.Context, arg1 string) (models.Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeocodeLocationAddress", arg0, arg1)
	ret0, _ := ret[0].(models.Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeocodeLocationAddress indicates an expected call of GeocodeLocationAddress.
func (mr *MockServiceIMockRecorder) GeocodeLocationAddress(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeocodeLocationAddress", reflect.TypeOf((*MockServiceI)(nil).GeocodeLocationAddress), arg0, arg1)
}
